// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shippings.Persistence.Contexts;

namespace Shippings.Persistence.Migrations
{
    [DbContext(typeof(ShippingsDbContext))]
    [Migration("20200512204758_AddShippingV3")]
    partial class AddShippingV3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Shipping")
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shippings.Domain.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("AppSetting");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2020, 5, 12, 20, 47, 57, 928, DateTimeKind.Utc).AddTicks(9140),
                            EntityStatus = 0,
                            Group = "Application",
                            IsReadOnly = true,
                            Name = "Version",
                            Value = "v1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2020, 5, 12, 20, 47, 57, 929, DateTimeKind.Utc).AddTicks(2240),
                            EntityStatus = 0,
                            Group = "Application",
                            IsReadOnly = true,
                            Name = "Owner",
                            Value = "admin"
                        });
                });

            modelBuilder.Entity("Shippings.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourierId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("BranchId");

                    b.HasIndex("CourierId");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("Shippings.Domain.Entities.Courier", b =>
                {
                    b.Property<int>("CourierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientCredentials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<string>("SellerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("CourierId");

                    b.ToTable("Courier");
                });

            modelBuilder.Entity("Shippings.Domain.Entities.Coverage", b =>
                {
                    b.Property<int>("CoverageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoverageType")
                        .HasColumnType("int");

                    b.Property<string>("CoverageValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("CoverageId");

                    b.HasIndex("BranchId");

                    b.ToTable("Coverage");
                });

            modelBuilder.Entity("Shippings.Domain.Entities.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourierId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverType")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("DriverId");

                    b.HasIndex("CourierId");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("Shippings.Domain.Entities.Provider", b =>
                {
                    b.Property<int>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CountryIsoCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProviderType")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ProviderId");

                    b.ToTable("Provider");

                    b.HasData(
                        new
                        {
                            ProviderId = 1,
                            Active = true,
                            CountryIsoCode = "PE",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2020, 5, 12, 20, 47, 57, 931, DateTimeKind.Utc).AddTicks(2200),
                            Description = "Chazki",
                            EntityStatus = 0,
                            Icon = "chazki",
                            Image = "chazki",
                            Label = "Chazki",
                            Name = "Chazki",
                            ProviderType = 0
                        },
                        new
                        {
                            ProviderId = 2,
                            Active = true,
                            CountryIsoCode = "PE",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2020, 5, 12, 20, 47, 57, 931, DateTimeKind.Utc).AddTicks(2710),
                            Description = "Urbaner",
                            EntityStatus = 0,
                            Icon = "urbaner",
                            Image = "urbaner",
                            Label = "Urbaner",
                            Name = "Urbaner",
                            ProviderType = 0
                        },
                        new
                        {
                            ProviderId = 3,
                            Active = true,
                            CountryIsoCode = "PE",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2020, 5, 12, 20, 47, 57, 931, DateTimeKind.Utc).AddTicks(2720),
                            Description = "Urbano",
                            EntityStatus = 0,
                            Icon = "urbano",
                            Image = "urbano",
                            Label = "Urbano",
                            Name = "Urbano",
                            ProviderType = 0
                        },
                        new
                        {
                            ProviderId = 4,
                            Active = true,
                            CountryIsoCode = "PE",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2020, 5, 12, 20, 47, 57, 931, DateTimeKind.Utc).AddTicks(2720),
                            Description = "Rappi",
                            EntityStatus = 0,
                            Icon = "rappi",
                            Image = "rappi",
                            Label = "Rappi",
                            Name = "Rappi",
                            ProviderType = 0
                        },
                        new
                        {
                            ProviderId = 5,
                            Active = true,
                            CountryIsoCode = "PE",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2020, 5, 12, 20, 47, 57, 931, DateTimeKind.Utc).AddTicks(2720),
                            Description = "Glovo",
                            EntityStatus = 0,
                            Icon = "glovo",
                            Image = "glovo",
                            Label = "Glovo",
                            Name = "Glovo",
                            ProviderType = 0
                        },
                        new
                        {
                            ProviderId = 6,
                            Active = true,
                            CountryIsoCode = "PE",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2020, 5, 12, 20, 47, 57, 931, DateTimeKind.Utc).AddTicks(2720),
                            Description = "Kurumi",
                            EntityStatus = 0,
                            Icon = "kurumi",
                            Image = "kurumi",
                            Label = "Kurumi",
                            Name = "Kurumi",
                            ProviderType = 1
                        });
                });

            modelBuilder.Entity("Shippings.Domain.Entities.ProviderSetting", b =>
                {
                    b.Property<int>("ProviderSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProviderSettingId");

                    b.HasIndex("ProviderId");

                    b.ToTable("ProviderSetting");

                    b.HasData(
                        new
                        {
                            ProviderSettingId = 1,
                            CreatedOn = new DateTime(2020, 5, 12, 20, 47, 57, 931, DateTimeKind.Utc).AddTicks(4090),
                            EntityStatus = 0,
                            IsReadOnly = true,
                            Key = "ClientId",
                            Label = "Client Id",
                            ProviderId = 6,
                            Value = "DF7BD349-1CFA-4B72-B612-376B5A1E76C9"
                        },
                        new
                        {
                            ProviderSettingId = 2,
                            CreatedOn = new DateTime(2020, 5, 12, 20, 47, 57, 931, DateTimeKind.Utc).AddTicks(6510),
                            EntityStatus = 0,
                            IsReadOnly = true,
                            Key = "ClientSecret",
                            Label = "Client Secret",
                            ProviderId = 6,
                            Value = "s5E5s3hgBZL6Hqc"
                        });
                });

            modelBuilder.Entity("Shippings.Domain.Entities.ProviderSettingTenant", b =>
                {
                    b.Property<int>("ProviderSettingTenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<int>("ProviderSettingId")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProviderSettingTenantId");

                    b.HasIndex("ProviderSettingId");

                    b.ToTable("ProviderSettingTenant");
                });

            modelBuilder.Entity("Shippings.Domain.Entities.ProviderTenant", b =>
                {
                    b.Property<int>("ProviderTenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ProviderTenantId");

                    b.HasIndex("ProviderId");

                    b.ToTable("ProviderTenant");
                });

            modelBuilder.Entity("Shippings.Domain.Entities.Rate", b =>
                {
                    b.Property<int>("RateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginId")
                        .HasColumnType("int");

                    b.Property<bool>("SupportCashOnDelivery")
                        .HasColumnType("bit");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("RateId");

                    b.HasIndex("BranchId");

                    b.ToTable("Rate");
                });

            modelBuilder.Entity("Shippings.Domain.Entities.RatePrice", b =>
                {
                    b.Property<int>("RatePriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("MaxWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceCOD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RateId")
                        .HasColumnType("int");

                    b.Property<int>("ShippingMethodTenantId")
                        .HasColumnType("int");

                    b.HasKey("RatePriceId");

                    b.HasIndex("RateId");

                    b.HasIndex("ShippingMethodTenantId");

                    b.ToTable("RatePrice");
                });

            modelBuilder.Entity("Shippings.Domain.Entities.Shipment", b =>
                {
                    b.Property<Guid>("ShipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryIsoCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyIsoCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<string>("SellerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShipmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShipmentExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ShipmentId");

                    b.HasIndex("ProviderId");

                    b.ToTable("Shipment");
                });

            modelBuilder.Entity("Shippings.Domain.Entities.ShippingMethod", b =>
                {
                    b.Property<int>("ShippingMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryIsoCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ShippingMethodId");

                    b.ToTable("ShippingMethod");

                    b.HasData(
                        new
                        {
                            ShippingMethodId = 1,
                            CountryIsoCode = "PE",
                            CreatedOn = new DateTime(2020, 5, 12, 20, 47, 57, 930, DateTimeKind.Utc).AddTicks(4930),
                            Description = "Express",
                            EntityStatus = 0,
                            IsPublished = false,
                            Label = "Express",
                            Name = "Express"
                        },
                        new
                        {
                            ShippingMethodId = 2,
                            CountryIsoCode = "PE",
                            CreatedOn = new DateTime(2020, 5, 12, 20, 47, 57, 930, DateTimeKind.Utc).AddTicks(7130),
                            Description = "Regular",
                            EntityStatus = 0,
                            IsPublished = false,
                            Label = "Regular",
                            Name = "Regular"
                        },
                        new
                        {
                            ShippingMethodId = 3,
                            CountryIsoCode = "PE",
                            CreatedOn = new DateTime(2020, 5, 12, 20, 47, 57, 930, DateTimeKind.Utc).AddTicks(7180),
                            Description = "Mismo o al día siguiente",
                            EntityStatus = 0,
                            IsPublished = false,
                            Label = "Same Or Next Day",
                            Name = "SameOrNextDay"
                        },
                        new
                        {
                            ShippingMethodId = 4,
                            CountryIsoCode = "PE",
                            CreatedOn = new DateTime(2020, 5, 12, 20, 47, 57, 930, DateTimeKind.Utc).AddTicks(7180),
                            Description = "Programado",
                            EntityStatus = 0,
                            IsPublished = false,
                            Label = "Programado",
                            Name = "Scheduled"
                        });
                });

            modelBuilder.Entity("Shippings.Domain.Entities.ShippingMethodTenant", b =>
                {
                    b.Property<int>("ShippingMethodTenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<int>("ShippingMethodId")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ShippingMethodTenantId");

                    b.HasIndex("ShippingMethodId");

                    b.ToTable("ShippingMethodTenant");
                });

            modelBuilder.Entity("Shippings.Domain.Entities.Branch", b =>
                {
                    b.HasOne("Shippings.Domain.Entities.Courier", "Courier")
                        .WithMany("Branches")
                        .HasForeignKey("CourierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shippings.Domain.Entities.Coverage", b =>
                {
                    b.HasOne("Shippings.Domain.Entities.Branch", "Branch")
                        .WithMany("Coverages")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shippings.Domain.Entities.Driver", b =>
                {
                    b.HasOne("Shippings.Domain.Entities.Courier", "Courier")
                        .WithMany("Drivers")
                        .HasForeignKey("CourierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shippings.Domain.Entities.ProviderSetting", b =>
                {
                    b.HasOne("Shippings.Domain.Entities.Provider", "Provider")
                        .WithMany("ProviderSettings")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shippings.Domain.Entities.ProviderSettingTenant", b =>
                {
                    b.HasOne("Shippings.Domain.Entities.ProviderSetting", "ProviderSetting")
                        .WithMany("ProviderSettingTenants")
                        .HasForeignKey("ProviderSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shippings.Domain.Entities.ProviderTenant", b =>
                {
                    b.HasOne("Shippings.Domain.Entities.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shippings.Domain.Entities.Rate", b =>
                {
                    b.HasOne("Shippings.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shippings.Domain.Entities.RatePrice", b =>
                {
                    b.HasOne("Shippings.Domain.Entities.Rate", "Rate")
                        .WithMany("Prices")
                        .HasForeignKey("RateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shippings.Domain.Entities.ShippingMethodTenant", "ShippingMethodTenant")
                        .WithMany("RatePrices")
                        .HasForeignKey("ShippingMethodTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shippings.Domain.Entities.Shipment", b =>
                {
                    b.HasOne("Shippings.Domain.Entities.Provider", "Provider")
                        .WithMany("Shipments")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shippings.Domain.Entities.ShippingMethodTenant", b =>
                {
                    b.HasOne("Shippings.Domain.Entities.ShippingMethod", "ShippingMethod")
                        .WithMany()
                        .HasForeignKey("ShippingMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
